name: "Resources Microservice"

on:
  push:
    branches: [ main ]
    paths:
      - "Reservea.API/Reservea.Microservices/Reservea.Microservices.Resources/**"
      - "Reservea.API/Reservea.Common/**"
      - "Reservea.API/Reservea.Persistance/**"
      - ".github/workflows/ResourcesMicroservice.yml"
jobs:
  build-and-deploy:
    env: 
      SERVICE_NAME: resourcesmicroservice
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Build'
      run: |
        cd Reservea.API
        docker build -f "Reservea.Microservices/Reservea.Microservices.Resources/Dockerfile" -t $SERVICE_NAME . 
    - name: 'Login to azure'
      uses: azure/docker-login@v1
      with:
        login-server: '${{ secrets.AZURE_CONTAINER_REGISTRY_URL }}'
        username: '${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}'
        password: '${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}'
    - name: 'Push to azure'
      run: |
        docker tag $SERVICE_NAME ${{ secrets.AZURE_CONTAINER_REGISTRY_URL }}/$SERVICE_NAME
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_URL }}/$SERVICE_NAME